# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bootcoin-microservice-ecalderc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4f4a68de6cef4abe87dd592d0744b1f6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2c4004691dcf4e21bd188c96c8f959c2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f4a68de6cef4abe87dd592d0744b1f6 }}/bootcoin-microservice:${{ github.sha }}
        file: /.github/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bootcoin-microservice-ecalderc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_16e7aecc147f492ea68064cccca52d4a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f4a68de6cef4abe87dd592d0744b1f6 }}/bootcoin-microservice:${{ github.sha }}'